language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nosetests
deploy:
  provider: gae
  keyfile: stravadora-fd82e64ea673.json
  project: stravadora
before_install:
- openssl aes-256-cbc -K $encrypted_579d7381f1bb_key -iv $encrypted_579d7381f1bb_iv
  -in stravadora-fd82e64ea673.json.enc -out stravadora-fd82e64ea673.json -d
